/* This file was generated by github.com/ronanyeah/elm-port-gen */

interface ElmApp {
  ports: Ports;
}

interface Ports {
  log: PortOut<string>;
  checkId: PortOut<number>;
  vanity: PortOut<any>;
  generatePow: PortOut<null>;
  stopGrind: PortOut<null>;
  openWalletMenu: PortOut<null>;
  mintNft: PortOut<number[]>;
  fileOut: PortOut<any>;
  idExists: PortIn<string | null>;
  addrCb: PortIn<string[]>;
  walletCb: PortIn<string>;
  startTimeCb: PortIn<number>;
  mintCb: PortIn<string>;
  grindCb: PortIn<{
    count: number;
    keys: Key[];
  }>;
  mintErr: PortIn<null>;
  nftCb: PortIn<Key>;
  vanityCb: PortIn<{
    count: number;
    keys: Vanity[];
  }>;
  availabilityCb: PortIn<number>;
  disconnect: PortIn<null>;
}

interface PortOut<T> {
  subscribe: (_: (_: T) => void) => void;
}

interface PortIn<T> {
  send: (_: T) => void;
}

interface Key {
  pubkey: string;
  parts: string[];
  bytes: number[];
  nft: {
    id: number;
    register: string;
  } | null;
}

interface Vanity {
  pubkey: string;
  bytes: number[];
}

export { ElmApp, Key, Vanity };